name: format-check

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    container: debian:stable-slim
    steps:

    - name: Install clang-format
      run: |
        apt-get update
        apt-get install -y curl git
        curl -SL https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-208096c1/clang-format-14_linux-amd64 > /usr/local/bin/clang-format
        chmod +x /usr/local/bin/clang-format

    - uses: actions/checkout@v2

    - name: Run format
      run: ci/format.sh .

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install black
        run: pip install black
      - name: Run formatting
        run: black --check .
